### PR TITLE
Handle old failed tasks on vCloud Entities

### PR DESCRIPTION
**Pull request by tlawrence**
vCloud maintains a list of historical tasks for a vApp. These tasks are returned in the Xml element of a GET vAPP response. 
When BOSH recomposes a vApp (to merge in new VMs for example) currently it aborts the BOSH Task if any failed tasks are identified. 
This PR enables a configurable time threshold @old_task_threshold which tells the vcd_client library to disregard tasks older than the value (in minutes). By default tasks older than an hour will be ignored.

This is an update version of:
https://github.com/cloudfoundry-attic/bosh_vcloud_cpi/pull/18

and relates to issue #10

### CODE REVIEW

**Comment by cppforlife** [comment]
thank you for refiling the pr so quickly. ill update the other repo with a deprecated notice (or may be even delete it, its been sitting inthe attic org for long time). we ll get to this pr this coming morning. i do see though that dreddbot is not finding cla on file. please follow its instructions and submit a cla so that we can merge this.

**Comment by tlawrence** [comment]
our commercial Director is sending the CLA this afternoon.

**Comment by tlawrence** [comment]
Chip has authorised our CLA now.

**Comment by cppforlife** [comment]
Available in v21.

**Pull request closed without merging**
